# FROM ubuntu:latest
FROM harbor.matrixport.dev/base_image/elastalert:v0.0.2

#RUN apt-get update && apt-get upgrade -y
#RUN apt-get -y install build-essential python3-pip libssl-dev git
#RUN apt-get -y install python3.6
# python3.6-dev

WORKDIR /home/elastalert

ADD requirements*.txt ./
ADD . /home/elastalert
RUN pip3 install -r requirements-dev.txt
RUN python3 setup.py install
